### ISSUE TITLE
Version check fails since repository move

### ISSUE THREAD

**Issue by snarkbe** [pi-hole/PADD#110]
The version check fails again, although I'm running the latest version 

This is caused by the move of the PADD repository from https://github.com/jpmck/PADD/ to https://github.com/pi-hole/PADD/ as 2 redirections are now needed, instead of one before.

Changing [line 493](https://github.com/pi-hole/PADD/blob/09e34ae56892a61518cf8cba854c40501924caf8/padd.sh#L493) to:
` padd_version_latest=$(curl -sI https://github.com/pi-hole/PADD/releases/latest | awk -F / 'tolower($0) ~ /^location:/ {print $NF; exit}' | tr -d '\r\n[:alpha:]')`
solves the issue.

**Comment by fireheadman** [comment]
thanks....  I provided some additional info (screenshots) if you need them.

**Comment by PromoFaux** [comment]
OK, I guess we need to make the change and tag a new version to fix this.  @snarkbe would you like to make a pull request with the proposed change?

@jpmck what's the standard way for releasing on this repo? Is it PRs into `development`, then `master`? Or just straight into `master`?

**Comment by peatrick** [comment]
Awesome, thanks you @snarkbe (et al).  This resolved things on both my Ubuntu Server 20.04 VM as well as my RPi3B+ running Raspbian GNU/Linux 10 Lite (buster).  Much obliged.

**Comment by dschaper** [comment]
Or use the same version check that the Core uses? https://github.com/pi-hole/pi-hole/blob/4d25f695267590b61a4061f9bb43448005d99b85/advanced/Scripts/updatecheck.sh#L52

**Comment by HinksUK** [comment]
I changed the URL to https://github.com/pi-hole/PADD/.. and it worked.
