### ISSUE TITLE
Certain stats not properly displaying in PADD v3.2.2

### ISSUE THREAD

**Issue by mokrunka** [pi-hole/PADD#112]
*Before submitting a bug report, are you using a test version of Pi-hole? If so, PADD doesn‘t support beta versions of Pi-hole!*

**Describe the bug**
under the 'STATS' section, Blocking shows '0 domains', Clients is blank, Latest is 0, Top Ad is blank, Top Dmn is blank, Top Clnt is blank. I have reason to believe that pi-hole itself is working since the web UI is updating and telling me ads are actively being blocked. This seems to be an issue with how the data is collected for printing to the screen in PADD.

**To Reproduce**
1. run ./padd.sh
2. observe missing information

**Expected behavior**
blocked ads and other data should be properly reported, and not blank.

**Screenshots**
![image](https://user-images.githubusercontent.com/59213927/87626981-88e77480-c6e2-11ea-8638-e7b7972e5fa9.png)

**Comment by Barokai** [comment]
same for me, happens since the update to 5.1.1

**Comment by snarkbe** [comment]
The FTL component doesn't write the file pihole-FTL.port anymore with the correct port to access the API. PADD uses this file to get the port to connect to the FTL API and retrieves the stats.

I changed [line 112](https://github.com/pi-hole/PADD/blob/master/padd.sh#L112) and hardcoded the port:
`ftl_port=4711`

This is a workaround of course. It should be solved the proper way, by dynamically retrieving the port. But each time I restarted FTL, it was always using port 4711 though.

**Comment by Fleegle61** [comment]
Tried changing line 112.  Didnt see any difference it results when I ran PADD again.

**Comment by snarkbe** [comment]
> Tried changing line 112. Didnt see any difference it results when I ran PADD again.
Changed to what? 
It works fine for me! 
![image](https://user-images.githubusercontent.com/38499432/87668715-e6280800-c76c-11ea-8354-4f57a3051a51.png)

**Comment by Fleegle61** [comment]
Strange.  I changed padd.sh to have line 112 use port 4711 as noted above.  Only on my 1st cup of java this morning.  Let me go back and double check..

**Comment by Fleegle61** [comment]
rebooted and still the same...Maybe I am not using port 4711?  Gotta dig a little deeper on this
![image](https://user-images.githubusercontent.com/68381023/87669658-61bd9100-c73c-11ea-8a31-bec5651887e0.png)

**Comment by snarkbe** [comment]
> Maybe I am not using port 4711? Gotta dig a little deeper on this

 `sudo lsof -Pi4 | grep pihole-FT`

and check the port listening on localhost only:
`pihole-FT 31642      pihole   13u  IPv4 4830919      0t0  TCP localhost:4711 (LISTEN)`

**Comment by Fleegle61** [comment]
Fat finger!  I used /padd.sh instead of ./padd.sh (since I had accidentally downloaded padd.sh into root folder and not user folder)

![image](https://user-images.githubusercontent.com/68381023/87670634-10160600-c73e-11ea-99ab-7d4760134a0d.png)

**Comment by mokrunka** [comment]
To make things a bit more robust, users can add an entry to /etc/pihole/pihole-FTL.conf as follows:

FTLPORT=4711

I think then the port number could be hardcoded into PADD.sh. I've spent some time looking through the source, but it's not clear to me exactly which code specifically assigns port 4711 for use.

piholeDebug.sh has a function in there to check the ports required for operation are available though - maybe something like this could be used to extract the port number for PADD? https://github.com/pi-hole/pi-hole/blob/56cd7c4d59ceb629a2170cd1c8ab78ef26366019/advanced/Scripts/piholeDebug.sh#L689

**Comment by snarkbe** [comment]
> piholeDebug.sh has a function in there to check the ports required for operation are available though - maybe something like this could be used to extract the port number for PADD?

It still has a reference to the now-obsolete port file:
`FTL_PORT="${RUN_DIRECTORY}/pihole-FTL.port"`

**Comment by mokrunka** [comment]
> > piholeDebug.sh has a function in there to check the ports required for operation are available though - maybe something like this could be used to extract the port number for PADD?
> 
> It still has a reference to the now-obsolete port file:
> `FTL_PORT="${RUN_DIRECTORY}/pihole-FTL.port"`

I was referring specifically to the notion of using lsof to source the port information for FTL.

**Comment by dschaper** [comment]
Until I can get FTL fixed the below will work. Don't modify PADD, no changes are needed there...

`echo 4711 | sudo tee /var/run/pihole-FTL.port`

**Comment by pheiduck** [comment]
After reboot its showing agian `FTL offline`

**Comment by dschaper** [comment]
Yeah, `/var/run` is a temporary filesystem that doesn't survive reboot.

**Comment by pheiduck** [comment]
hm so we have to wait for a Fixed Version?

**Comment by dschaper** [comment]
Or run the command again.

**Comment by mokrunka** [comment]
you can also edit (at your own risk) the ./padd.sh script on line 112 to read:
`ftl_port=4711`
until the pi-hole source is updated to once again write the port to the pihole-FTL.port file.

**Comment by pheiduck** [comment]
is there a way to hide the echo of `4711` ?

**Comment by snarkbe** [comment]
`echo 4711 >/var/run/pihole-FTL.port`

**Comment by dschaper** [comment]
That only works if you're already root.

**Comment by PureFallen** [comment]
> is there a way to hide the echo of `4711` ?

> `echo 4711 >/var/run/pihole-FTL.port`

won't work, even if you `sudo echo`.
If you are worried about echo being displayed on the PADD on display later: This should be gone as soon as PADD refreshes, especially since you only need to run this echo once each time the system is restarted.

One option to hotfix that for the moment could be to create that file in the reboot before ./padd.sh is executed.

**Comment by dschaper** [comment]
I've already got the update to FTL submitted as a PR, I'm waiting for confirmation that it works and doesn't break something else. The rest of the team will be able to do that when they have a few moments or are awake in their respective time zones.

**Comment by Fleegle61** [comment]
Gotta love the quick response!  Thanks Dan

**Comment by vekzla** [comment]
![20200717_174843](https://user-images.githubusercontent.com/47047226/87766704-ed2e4380-c85c-11ea-93e5-0ccb7755d764.jpg)
Same here boys and girls, happened post pihole -up

**Comment by dschaper** [comment]
Is this showing anything different than the previous 23 posts already covered?

**Comment by vekzla** [comment]
> Is this showing anything different than the previous 23 posts already covered?

Not at all mate,

**Comment by PureFallen** [comment]
> Not at all mate,

The "hotfix" solution is already digged under the existing replies, and that screenshot doesn't really help finding it any faster for the next one arriving here.

As said from @dschaper before:
> Until I can get FTL fixed the below will work. Don't modify PADD, no changes are needed there...
> 
> `echo 4711 | sudo tee /var/run/pihole-FTL.port`

I think that is everything that needs to be said.

**Comment by dschaper** [comment]
Following up: The fix is set for the next release of FTL but there's a couple of more FTL issues we'd like to get in the same release. Since there's a quick workaround for this cosmetic issue (see the post directly above this one) we think it's okay to wait a day or two.

**Comment by dschaper** [comment]
Sorry this took a lot longer than I intended but it should now be resolved.

**Comment by dschaper** [comment]
Should all be working now.
