### ISSUE TITLE
pihole -c show FTL offline on LCD

### ISSUE THREAD

**Issue by pheiduck** [pi-hole/PADD#114]
echo 4711 > /var/run/pihole-FTL.port didn't resolve it on my LCD have a Script to execute it > https://discourse.pi-hole.net/t/set-5-display-on-pi-hole-to-show-stats/17756/3

_Originally posted by @pheiduck in https://github.com/pi-hole/pi-hole/issues/3558#issuecomment-659602559_

**Comment by dschaper** [comment]
Duplicate of #112
