### ISSUE TITLE
Screen orientation

### ISSUE THREAD

**Issue by chrisjeb** [pi-hole/PADD#117]
Hi,

Since the update my 3.5screen seems to be stuck upside down. If i go in desktop mode its fine but as soon as i boot in padd it turn upside down. Have edited boot.txt and this does not seem to work anymore. Any help is appreciated.

**Comment by mycomachine** [comment]
try running sudo ./adafruit-pitft.sh again, you can change orientation there use 90 or 270 degrees depending on orientation
