### ISSUE TITLE
DNS Section doesn't work properly

### ISSUE THREAD

**Issue by lastsamurai26** [pi-hole/PADD#124]
*Before submitting a bug report, are you using a test version of Pi-hole? If so, PADD doesn‘t support beta versions of Pi-hole!*

**Describe the bug**
When PADD is executed, the data is read in, but some are not read in correctly. 
CONDITIONAL FORWORDING 
is displayed as deactivated although activated 

**To Reproduce**
1. Download padd.sh
2. chmod +x padd.sh 
3. ./padd.sh  works with sudo ./padd.sh

**Expected behavior**
CONDITIONAL FORWORDING should be displayed as active

**Screenshots**
![Bildschirmfoto 2020-09-14 um 22 22 49](https://user-images.githubusercontent.com/3257844/93136335-08da8c80-f6dc-11ea-8118-8701f289f2ef.png)

**Additional context**

**Comment by dschaper** [comment]
Fixed in #126, now in master.
