### ISSUE TITLE
If Pi-Hole is running on VM don't show CPU Temp in PADD

### ISSUE THREAD

**Issue by tmburton** [pi-hole/PADD#137]
When Pi-Hole is installed on a VM the CPU Temp is shown as "CPU Temp: 32.0°F" in PADD

Instead maybe we could show 0F/Unknown/VM or some other status.

Another option would be to remove CPU temp all together but unsure of what to put in that space or just have empty space.

**Comment by tgjohnst** [comment]
I have created a PR to address this issue - please check it out and see if this is a fix that would address your feature request

**Comment by tmburton** [comment]
Yes, I think this would work. Thank you

**Comment by thomasmerz** [comment]
Why has the PR been closed without merging? I still see "CPU Temp: 0.0°C" on my VMs…

**Comment by PromoFaux** [comment]
From the PR 

> I'm going to close this PR and make a cleaner one in its place once I solve it.

**Comment by thomasmerz** [comment]
@tgjohnst , didn't you want to make a "cleaner" PR for this one? 🤔 I really would like not seing "CPU Temp: 0.0°C" anymore on my VMs.
