### ISSUE TITLE
Showing CPU Temp in C in PADD when Pi-Hole Web Interface is set to F

### ISSUE THREAD

**Issue by tmburton** [pi-hole/PADD#138]
Running Pi-hole v5.1.2 Web Interface v5.1.1 FTL v5.2 and PADD v3.4 on a Raspberry Pi 4

Web interface is set to Fahrenheit:

![image](https://user-images.githubusercontent.com/63884201/95237382-bddd0200-07cd-11eb-9d6a-a0bc3042e456.png)

![image](https://user-images.githubusercontent.com/63884201/95237395-c5041000-07cd-11eb-810c-ddaba34f2555.png)

But PADD is showing Celsius:
CPU Temp: 44.8°C 

I believe that it should be showing Fahrenheit, is there something I am missing?

Thank you

**Comment by tmburton** [comment]
I just noticed "Styling (auto saved, per-browser)" so that would appear its a client cookie that is saving it to be F and not in the actual Pi-hole config.

How can I resolve this?

**Comment by dschaper** [comment]
It should also be in `/etc/pihole/setupVars.conf` as a variable.

**Comment by tmburton** [comment]
Thank you, I added TEMPERATUREUNIT=F to /etc/pihole/setupVars.conf

I know its not a part of PADD per se but since PADD relies on the data, do you think it would be beneficial to add this information to the Wiki?


To change Pi-Hole temp reporting and for PADD to display the unit type desired modify the following:
/etc/pihole/setupVars.conf

For Fahrenheit add:
TEMPERATUREUNIT=F

For Celsius add:
TEMPERATUREUNIT=C

For Kevlin add:
TEMPERATUREUNIT=K

Restart the Pi-Hole service and then PADD for it to take effect
sudo systemctl restart pihole-FTL.service
