### ISSUE TITLE
PADD Version Inconsistent (v3.4 then v3.3.1)

### ISSUE THREAD

**Issue by draik** [pi-hole/PADD#142]
When I start padd.sh, it shows as being v3.4, and everything is green in the version check, along with "Your system is healthy." message. Once it refreshes, it shows PADD as version 3.3.1, and "[i] Updates are available." is shown. The PADD version remains v3.3.1, but text color alternates between red (version mismatch, line 521) and green (else, line 524) after each refresh.

I've removed padd.sh, and pulled the latest version using "wget -N https://raw.githubusercontent.com/pi-hole/PADD/master/padd.sh" but the results are the same.

I've checked with the JSON output used to check for the latest version, and it has the tag_name value "v3.4", just like padd_version variable (line 20) in padd.sh.

(nitpicking: a few lines with trailing spaces in the latest padd.sh)

**Comment by dschaper** [comment]
I don't know what would cause that as https://github.com/pi-hole/PADD/blob/master/padd.sh#L20 clearly is `v3.4` and there's no `v3.3.1` string anywhere in the script.

Is it possible that the filesystem is read-only or something like a script is automatically overwriting the `padd.sh` file?

**Comment by draik** [comment]
I'm not sure where it's reading it from, but the piHoleVersion file output shows the variable as "v3.3.1" for some reason

```
last_check=20201030
core_version=5.1.2
core_version_latest=5.1.2
core_version_heatmap=
web_version=5.1.1
web_version_latest=5.1.1
web_version_heatmap=
ftl_version=5.2
ftl_version_latest=5.2
ftl_version_heatmap=
padd_version=v3.3.1
padd_version_latest=v3.4
padd_version_heatmap=
version_status="PADD is out-of-date!"
version_heatmap=
version_check_box="[✗]"
pico_status="[i] Update"
mini_status_="[i] Update avail."
tiny_status_="[i] Updates are available."
full_status_="[i] Updates are available."
```

The filesystem is not read-only, and padd.sh remains with `padd_version="v3.4"` on line 20.

**Comment by dschaper** [comment]
What's the file permissions on the version file?

```plain
dan@raspberrypi:~ $ ls
PADD.pid  padd.sh  piHoleVersion
dan@raspberrypi:~ $ cat piHoleVersion
last_check=20201030
core_version=5.1.2
core_version_latest=5.1.2
core_version_heatmap=
web_version=5.1.1
web_version_latest=5.1.1
web_version_heatmap=
ftl_version=5.2
ftl_version_latest=5.2
ftl_version_heatmap=
padd_version=v3.4
padd_version_latest=v3.4
padd_version_heatmap=
version_status="Pi-hole is up-to-date!"
version_heatmap=
version_check_box="[✓]"
pico_status="[✓] Sys. OK"
mini_status_="[✓] System OK"
tiny_status_="[✓] System is healthy."
full_status_="[✓] System is healthy."
dan@raspberrypi:~ $ ls -la piHoleVersion
-rw-r--r-- 1 dan dan 578 Oct 30 11:56 piHoleVersion
```

**Comment by draik** [comment]
File is in /usr/bin/
`-rwxr-xr-x 1 root root 48K Oct 30 10:55 /usr/bin/padd.sh`

**Comment by dschaper** [comment]
Okay, but I asked for the `piHoleVersion` file.

**Comment by draik** [comment]
Sorry. That's in ~/
`-rw-r--r-- 1 root root 577 Oct 30 12:02 piHoleVersion`

**Comment by dschaper** [comment]
And what user is running `padd.sh`?

**Comment by draik** [comment]
My user with sudo. I granted it sudo permission in /etc/sudoers

**Comment by dschaper** [comment]
Does that user have the ability to write that file? 

Remove the file and run PADD again, and updating your packages would be good to do at the same time.

**Comment by draik** [comment]
My user cannot write to the piHoleVersion file. It is only writable by root.

Running "sudo /usr/bin/padd.sh" results in the same v3.3.1 output.
Packages are up to date.

**Comment by dschaper** [comment]
Then PADD can not write to that file and can not update it with the current information.

This isn't a PADD bug or issue, it's how you've decided to run it.

**Comment by draik** [comment]
I've copied padd.sh to my home directory.
Running "~/padd.sh" creates the files as my user, but the issue remains.

`-rw-r--r-- 1 draik draik  576 Oct 30 12:23 piHoleVersion`

**Comment by dschaper** [comment]
`padd_version_latest=` seems to show that PADD can't contact GitHub for the latest version.

I can't replicate this, hopefully someone else has more ideas.

**Comment by dschaper** [comment]
Last thing to check is:

`grep v3 ~/padd.sh`

**Comment by draik** [comment]
```
grep v3 ~/padd.sh
padd_version="v3.4"
```

**Comment by dschaper** [comment]
I don't know what to tell you, there's absolutely nothing in `~/padd.sh` that could output `v3.3.1`

**Comment by draik** [comment]
That's exactly where I'm at a loss, too. It's the weirdest bug when it writes to the piHoleVersion file

**Comment by dschaper** [comment]
What kind of modifications have you made? Are you sourcing the file or loading values in to the environment?
Does
```
env | grep padd
```
or
```
export | grep padd
```
show anything in the current frame?

**Comment by draik** [comment]
I have zero output running either of those commands. I can't find anything that would get "v3.3.1" to output to the piHoleVersion file.

**Comment by dschaper** [comment]
I guess you could try `bash -x ~/padd.sh` and see the verbose output for wiring the versions file.

**Comment by draik** [comment]
I figured it out. Decided to check for any conflicting piHoleVersion files, using `sudo find / -type f -name piHoleVersion`.

There was one in /usr/bin/piHoleVersion somehow. Upon deleting that file, all is well now. It must have been going back and forth between reading that file, and the new file in ~/. Thanks for the help, and sorry for the trouble.
