### ISSUE TITLE
pihole-ftl v.5.3.4 / PADD v3.5.1 / pihole -c ---- telnet_connection_handler_thread 

### ISSUE THREAD

**Issue by un99known99** [pi-hole/PADD#152]
*Before submitting a bug report, are you using a test version of Pi-hole? If so, PADD doesn‘t support beta versions of Pi-hole!*

**Describe the bug**
pihole-FTL.log, error message
[2021-01-12 19:38:04.186 2402/T5429] WARN: Could not recv() in telnet_connection_handler_thread() (/root/project/src/api/socket.c:319): Connection reset by peer

was mentioned to be solved in new ftl version, but even after todays update, still issues in logfile
(https://github.com/pi-hole/PADD/issues/147#)
strange, seems to be an update loop, pihole -up showing up FTL update, after some time calling again pihole -up and again showing up with FTL update?!?

screenshots with pihole ftl update loop see here:
https://discourse.pi-hole.net/t/pihole-c-causes-pihole-ftl-log-errors-ftl-v5-3-4/42154

**To Reproduce**
1. tail -f pihole-FTL.log

**Expected behavior**
No errors in logfile

**Screenshots**

**Additional context**

**Comment by dschaper** [comment]
https://github.com/pi-hole/pi-hole/pull/3987
