### ISSUE TITLE
PADD cuts halfway down screen

### ISSUE THREAD

**Issue by Ginkozard** [pi-hole/PADD#154]
**Describe the bug**
After installing a fresh setup of RaspiOS, Pi-Hole, and PADD, the output of PADD is capped at the upper half of the screen. (See attached image)

**To Reproduce**
1. Fresh install of RaspiOS
2. Fresh install of PiHole (no custom config)
3. Follow the instructions [here to install PADD](https://github.com/pi-hole/PADD)

**Expected behavior**
PADD Should fill the entire screen, not just the top half

**Screenshots**
![PADD](https://user-images.githubusercontent.com/78051923/105911120-7a620a00-5fef-11eb-802f-2bc812f5b1e8.jpg)

**Additional context**
The screen that I'm using is a Waveshare 3.5 in (B) rev. 2

**Comment by dschaper** [comment]
https://www.reddit.com/r/pihole/comments/l5p1ag/padd_only_displays_on_top_half_of_screen_after/
