### ISSUE TITLE
Pi-Hole version is not detected and displayed

### ISSUE THREAD

**Issue by slodown** [pi-hole/PADD#157]
Hi,

I'm using Pi-hole v5.2.4 / Web Interface v5.4  / FTL v5.7 and PADD 3.5.1. 

During verifying at startup the version could not be detected.

![2021-03-04_235306](https://user-images.githubusercontent.com/49473911/110042295-df72f300-7d45-11eb-95ec-78a5c213bd15.png)

```
pi:~ $ cat piHoleVersion
last_check=20210305
core_version=
core_version_latest=
core_version_heatmap=
web_version=
web_version_latest=
web_version_heatmap=
ftl_version=
ftl_version_latest=
ftl_version_heatmap=
padd_version=v3.5.1
padd_version_latest=v3.5.1
padd_version_heatmap=
version_status="Pi-hole is up-to-date!"
version_heatmap=
version_check_box="[✓]"
pico_status="[✓] Sys. OK"
mini_status_="[✓] System OK"
tiny_status_="[✓] System is healthy."
full_status_="[✓] System is healthy."
```

Many thanks!

**Comment by dschaper** [comment]
What does `pihole -v` return for versions?

**Comment by slodown** [comment]
```
pi:~ $ pihole -v
  Current Pi-hole version is v5.2.4.
  Current AdminLTE version is v5.4.
  Current FTL version is v5.7.
```

**Comment by dschaper** [comment]
Stop PADD, remove `piHoleVersion` and then restart and see if that clears out.

**Comment by slodown** [comment]
This has not changed the behavior.

**Comment by slodown** [comment]
I do not know why, but now it is showing the version information.
