### ISSUE TITLE
PADD not displaying information

### ISSUE THREAD

**Issue by LuxStatera** [pi-hole/PADD#158]
*Before submitting a bug report, are you using a test version of Pi-hole? If so, PADD doesn‘t support beta versions of Pi-hole!*

**Describe the bug**

I dont think this is a bug but I am not sure why my display looks different than all the pictures people post. My display doesn't show the long green and red bar, the temp, the groups like system and network. it shows all the standard info but not everything. so im not sure if this is just how the new version looks or if i did something incorrectly.
**To Reproduce**
1. installed PADD on my raspberry pi 0 W that already had pihole on it
2. setup hdmi for PADD
3. reboot system to start PADD
4. It displays the information and is running and active but doesnt show ALL the information

**Expected behavior**
i expected my display to look the same as the picture on github
**Screenshots**
If applicable, add screenshots to help explain 
**Additional context**

**Comment by dschaper** [comment]
What are the dimensions of the screen? It looks like you have the Tiny display.

**Comment by LuxStatera** [comment]
"UCTRONICS 7 Inch IPS Touchscreen for Raspberry Pi 1024×600 Capacitive HDMI LCD Monitor Portable Display"

is there a way to switch to the normal display?

**Comment by LuxStatera** [comment]
![20210401_162728](https://user-images.githubusercontent.com/73693443/113372167-dbbe9600-931c-11eb-94d3-7f1524d93a95.jpg)

**Comment by dschaper** [comment]
Size display is determined with a couple of `tput` calls:

https://github.com/pi-hole/PADD/blob/master/padd.sh#L1201

What is the output from:

```bash
tput cols
tput lines
```

**Comment by LuxStatera** [comment]
cols 81
lines 38

**Comment by dschaper** [comment]
Sorry, that display isn't PADD. Where did you download the script from?

**Comment by LuxStatera** [comment]
i followed the "Setup PADD" on the README.md

**Comment by dschaper** [comment]
Then something is not configured correctly. The default display shows "PADD" not "Pi-hole". 

Have you made any modifications?

**Comment by LuxStatera** [comment]
i think i made an adjustment for hdmi. ill try to start fresh. how would i go about uninstalling it?

**Comment by dschaper** [comment]
There's nothing to install or uninstall. It's just a script that is run via `bash`.

**Comment by LuxStatera** [comment]
sorry im a noob. i appreciate the help. im going to reflash the sd card and start fresh

**Comment by dschaper** [comment]
You don't need to do all that. It's just a script call `padd.sh` in your home directory.

**Comment by LuxStatera** [comment]
i deleted it and removed the setting from the ./bashrc but it still pops up after a reboot

**Comment by dschaper** [comment]
Did you follow another persons guide or use another persons code like (https://gist.github.com/giuliomagnifico/39f9912a078418c1fdcb36d588ab3630?

**Comment by LuxStatera** [comment]
![Screenshot_20210401-205720_Chrome](https://user-images.githubusercontent.com/73693443/113378858-e97c1780-932c-11eb-9e8d-8617c32e388d.jpg)

**Comment by LuxStatera** [comment]
followed this page. i am using a raspberry pi zero w if that changes things

**Comment by dschaper** [comment]
The problem is that the logo you are showing just doesn't exist in this repo's code. It does exist in that code that I linked.

**Comment by LuxStatera** [comment]
![NC9C4fT](https://user-images.githubusercontent.com/73693443/113379488-85f2e980-932e-11eb-8d13-73c23d756253.jpg)

**Comment by LuxStatera** [comment]
ive seen it in a few other places so i assumed it was correct. not sure what i did

**Comment by dschaper** [comment]
That's not PADD.

Do you have any files that end in .sh in your home directory?

**Comment by LuxStatera** [comment]
nothing in my home directory

**Comment by LuxStatera** [comment]
i might be mistaken but if its the main directory i boot to then its also empty

**Comment by dschaper** [comment]
Then I'm not understanding how a file that doesn't exist can be started...

**Comment by LuxStatera** [comment]
its all good. im just gonna reflash it and try again. once again thank you for the help

**Comment by LuxStatera** [comment]
started fresh. reflashed. installed and setup pihole. "cd ~" then "wget -N https://raw.githubusercontent.com/pi-hole/PADD/master/padd.sh" then made it executable and setup auto run. i reboot my pi and it just brings me to the command line and PADD doesnt show. am i doing something wrong?

**Comment by LuxStatera** [comment]
![20210401_234118](https://user-images.githubusercontent.com/73693443/113388908-ed676400-9343-11eb-984b-8fa7daf974be.jpg)

**Comment by dschaper** [comment]
Great!

**Comment by jwebbstevens** [comment]
I know this issue is closed but I have the same setup.

It's important to make sure the Raspberry Pi 4 (etc) boots to the Command Line.

`raspi-config` and then follow the prompts as follows:

1. Select Menu Option 1 called _System Options_
2. Select Menu Option S5 called _Boot / Auto Login_
3. Select Menu Option B2 called _Console Autologin_

what this does is on boot the pi will always login automatically to the Console.

This assumes everything else is setup correctly including HDMI0 as the main interface to the screen.
