### ISSUE TITLE
CPU Load on RasPi Zero hovering at 110%-140%

### ISSUE THREAD

**Issue by ASchneider-GitHub** [pi-hole/PADD#172]
**Describe the bug**
Downloading the most recent version of `padd.sh` from the GitHub and running it on a RasPi Zero with PiHole shows the CPU load consistently over 100% and rarely sinks below it.

**To Reproduce**
1. `wget https://raw.githubusercontent.com/pi-hole/PADD/master/padd.sh`
2. `chmod +x ./padd.sh`
3. `./padd.sh`

**Expected behavior**
"CPU Load" should be somewhat close to what `htop` is seeing, which is much lower (although spikes every 5 seconds when PADD is running, which I assume is the data gathering method running)

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/65742424/130532578-859cf8e5-5148-438c-98c4-6a97a028248b.png)

**Comment by ASchneider-GitHub** [comment]
This issue can be closed. I realize now that disabling `newrelic-infra` service and waiting a while slowly brings the `CPU Load` back down to 50ish%. Turns out it can't run the New Relic agent at the same time as PADD. It has to be one or the other for some reason.

**Comment by dschaper** [comment]
CPU Load looks pretty close to your load averages?

**Comment by ASchneider-GitHub** [comment]
Hey there. This issue can be closed. I misinterpreted the readout of `htop` and thought the totals were way off. My bad!
