### ISSUE TITLE
piHoleVersion: line 9: unexpected EOF while looking for matching `)'

### ISSUE THREAD

**Issue by captcarl13** [pi-hole/PADD#174]
*Before submitting a bug report, are you using a test version of Pi-hole? If so, PADD doesn‘t support beta versions of Pi-hole!*

**Describe the bug**
piHoleVersion: line 9: unexpected EOF while looking for matching `)'

**To Reproduce**
1. Update pi-hole to  core 5.5, web 5.7, FTL 5.10
2. Run PADD

**Expected behavior**
PADD expected to run with no error.

**Screenshots**
![Screen Shot 2021-09-29 at 19 47 29](https://user-images.githubusercontent.com/867543/135363710-84c00d9c-e0cb-4f00-b1ed-ccd30365273f.png)

**Additional context**
On PADD v3.6.2 (current release)

**Comment by captcarl13** [comment]
Updated FTL again to 5.10.1 and issue appears resolved.

**Comment by rowlesmr** [comment]
I have the exact same problem with PADDmini

Pi-hole v5.5
AdminLTE v5.7
FLT v5.10.2

**Comment by captcarl13** [comment]
I just updated and I'm not getting the same error, but version numbers are not appearing.
![image](https://user-images.githubusercontent.com/867543/135612989-e44e069a-c33f-44c1-824e-bd55d104aee5.png)
![image](https://user-images.githubusercontent.com/867543/135613017-d480e17e-0334-4e66-b83d-62212f08db91.png)

**Comment by rowlesmr** [comment]
There is a fix here https://github.com/pi-hole/PADD/issues/175#issuecomment-931966859

**Comment by captcarl13** [comment]
#175 fixed my issue with `pihole -r.` Marking as closed.
