### ISSUE TITLE
PADD says updates available when they are not

### ISSUE THREAD

**Issue by JansonBHong** [pi-hole/PADD#175]
I am running PI-Hole on a Raspberry Pi 4b with a full updated Buster. I have the latest PADD and all was working well until I updated Pi-Hole to the latest version today. PADD says Core and FTL are up to date but that updates are still available. The last line displayed on the screen  or the PADD display is

SYSTEM ========================================================================
 Uptime:   0 days, 2 hours, 54 minutes             Memory:   [■·········] 13.2% 
 CPU Temp: 43.3°C    CPU Load: 1.31, 0.86, 0.67    CPU Load: [■■■■■■■■■■] 131.0%piHoleVersion: line 9: unexpected EOF while looking for matching `)'

**Comment by surtarso** [comment]
piHoleVersion: line 9: unexpected EOF while looking for matching `)'

gettin that same line in the end here

**Comment by snoopyh42** [comment]
Seeing the same on my system.

**Comment by enriqueardieanbudiono** [comment]
same problem here

**Comment by enriqueardieanbudiono** [comment]
I got a temporary solution:
- type vim ./piHoleVersion
- go to ftl_version=
- fill the version number
- go to ftl_version_latest
- fill it with the same version number

NOTE:

This is only temporary, if you restart the pi, it will show the error again

**Comment by kagegoomba** [comment]
Seeing the same issue here.
Tried the trick that enriqueardieanbudiono - nice temp fix that makes the screen look decent. I'll watch this thread for updates. ^_^

**Comment by MrClever** [comment]
Looks like `pihole -v -f` spits out additional words which is breaking the indexes in `padd.sh`.

Fixed with this patch
```bash
--- /GitHubSource/PADD/padd.sh 2021-09-14 21:46:40.605798260 +1000
+++ padd.sh 2021-10-01 17:04:07.366645991 +1000
@@ -527,8 +527,8 @@
 
     # Gather FTL version information...
     read -r -a ftl_versions <<< "$(pihole -v -f)"
-    ftl_version=$(echo "${ftl_versions[3]}" | tr -d '\r\n[:alpha:]')
-    ftl_version_latest=${ftl_versions[5]//)}
+    ftl_version=$(echo "${ftl_versions[4]}" | tr -d '\r\n[:alpha:]')
+    ftl_version_latest=${ftl_versions[6]//)}
     if [[ "${ftl_version_latest}" == "ERROR" ]]; then
       ftl_version_heatmap=${yellow_text}
     else
```

**Comment by JansonBHong** [comment]
Working perfectly - many thanks

**Comment by yubiuser** [comment]
@MrClever 

Can you file a pull request to fix this?

**Comment by MrClever** [comment]
Sure - will need to do the whole branch and fix dance. Give me a few minutes 👍🏻

**Comment by kagegoomba** [comment]
Can confirm the hotfix works - I edited the file manually myself as I need to get to bed - but I can at least say it fixes the issue. :)
Much thanks!

**Comment by MrClever** [comment]
PR #176 created :)

**Comment by yubiuser** [comment]
The reason for the issue has been identified. Pi-hole switched from CI to GHA to build the binaries. This introduced an additionally `release` in the versions output. Please run `pihole -r` to fetch the new builds which should have corrected this.

**Comment by MrClever** [comment]
Ran `pihole -r` and just did a repair. Then ran `pihole -v -f` again and it's back to the original output, so this issue goes away. Without the need for PR #176 

```
pihole -v -f
  FTL version is v5.10.2 (Latest: v5.10.2)
```

**Comment by yubiuser** [comment]
Thanks for confirming :)

**Comment by MrClever** [comment]
For the sake of absolute clarity, the current `padd.sh` release (v3.6.2) works without modification after doing the repair (`pihole -r`) and the changes proposed in #176 are not required..

**Comment by captcarl13** [comment]
Can confirm repair with `pihole -r` corrects issue, making my issue #174 irrelevant.

**Comment by kagegoomba** [comment]
Confirming that doing a pihole -r fixed the issue and after restoration of padd.sh

Nice to see a helpful community. :) Much thanks everyone.
