### ISSUE TITLE
PADD display issue

### ISSUE THREAD

**Issue by dynamix911** [pi-hole/PADD#179]
Hello,

Can CPU Temp be added to the PADDmini display. I have a 2.8" adafruit display, and there is plenty of room at the bottom to add CPU Temp. I have tried to modify the padd.sh file to add it, and did not work.

Thank You

**Comment by dynamix911** [comment]
Buy running sudo dpkg-reconfigure console-setup, and changing the font to 6x12. My whole screen gets filled with all the info and looks great. It switches to PADD Tiny from PADD Mini. How can i keep it at this size? on reboot it reverts back to the mini size and then i have the lower half of the screen empty. Have to run a sudo dpkg-reconfigure console-setup and change font to 6x12.

I also have this strange screen that pops up every 30 sec or so
![PADD-error](https://user-images.githubusercontent.com/94667774/142745609-f0c547cf-f075-421e-afa4-c3982ff503f1.jpg)

**Comment by yubiuser** [comment]
For "mini" to be active, the screen needs at least 40x18 (columns x lines). But then there is no space left to include CPU temp.
![Bildschirmfoto zu 2022-08-20 09-53-20](https://user-images.githubusercontent.com/26622301/185758862-5b33548c-8ae1-4209-be3f-9db58172b442.png)

The only option I see is shrinking the load bar and placing it on the right. But this would render the bar pretty meaningless....
