### ISSUE TITLE
FTL v5.13 and Core v5.8 broken the connection to FTL

### ISSUE THREAD

**Issue by giuliomagnifico** [pi-hole/PADD#183]
**Describe the bug**
Latest FTL v5.13 and Core v5.8 update has changed the way FTL checks and gets the datas. Here more infos: https://github.com/pi-hole/pi-hole/pull/4485/commits/f45248df805c426f9d9e654c0f71eb1fd8b795e8 

The results is unknow status, changes must be made here:

```
GetFTLData() {
  local ftl_port LINE
     ftl_port=$(cat /run/pihole-FTL.port 2> /dev/null)
     if [[ -n "$ftl_port" ]]; then
         # Open connection to FTL
         exec 3<>"/dev/tcp/127.0.0.1/$ftl_port"

         # Test if connection is open
         if { "true" >&3; } 2> /dev/null; then
             # Send command to FTL and ask to quit when finished
             echo -e ">$1 >quit" >&3

             # Read input until we received an empty string and the connection is
             # closed
             read -r -t 1 LINE <&3
             until [[ -z "${LINE}" ]] && [[ ! -t 3 ]]; do
                 echo "$LINE" >&1
                 read -r -t 1 LINE <&3
             done

             # Close connection
             exec 3>&-
             exec 3<&-
         fi
     else
         echo "0"
     fi

```

**Screenshots**
![Screen Shot 2022-01-06 at 08 45 40](https://user-images.githubusercontent.com/1975176/148348254-64eb5a55-0e5e-44e2-9523-364c32aa310d.jpeg)

**Comment by yubiuser** [comment]
This issue is fixed by
https://github.com/pi-hole/PADD/pull/182

But you found a place that could be improved 😉

**Comment by A12BA5E** [comment]
I confirm same issue.

**Comment by giuliomagnifico** [comment]
@A12BA5E change the line 422 https://github.com/pi-hole/PADD/pull/182/files with the updated line and it will work again

![Screen Shot 2022-01-06 at 10 29 13](https://user-images.githubusercontent.com/1975176/148361015-849e82b6-8033-493e-86e5-3956cdf682e1.png)
 
@yubiuser thanks for the reply, i fixed it.

**Comment by A12BA5E** [comment]
@giuliomagnifico Did the trick! Thank you!

**Comment by yubiuser** [comment]
This was fixed by https://github.com/pi-hole/PADD/pull/182
