### ISSUE TITLE
PADD display issue

### ISSUE THREAD

**Issue by A12BA5E** [pi-hole/PADD#184]
*Before submitting a bug report, are you using a test version of Pi-hole? If so, PADD doesn‘t support beta versions of Pi-hole!*
No.

**Describe the bug**
Under PADD section ‚Network‘ ‚IPv6:‘ follows a ‚+‘ after the last digit of the IPv6 address like
IPv6:     2003:c2:8f12:4002:36f3:ce24:77c9:8e1a+
(5 spaces before and 4 spaces behind left on display, so no wrap around).
This display state ‚+‘ is stable and not sporadic, regardless of a changed IPv6 address.

**To Reproduce**
1. sudo reboot
2. power off/on

**Expected behavior**
No additional characters behind an IP address if this is not joined to an intended functionality.

**Screenshots**
n/a, verbal bug description says it all.

**Additional context**
Raspberry Pi OS legacy lite, latest lcd35 driver, UTF-8 Terminus 6x12, in regular display mode.

**Comment by yubiuser** [comment]
This is not a but, it's a feature. It indicates, that more than one IPv6 address is available to your device.

https://github.com/pi-hole/PADD/blob/f96db79b25af1d4f5c69a7b85229862e45619551/padd.sh#L295-L299
