### ISSUE TITLE
External Address for Pi-hole

### ISSUE THREAD

**Issue by EndreEndi** [pi-hole/PADD#187]
So, i want to install PADD onto a Linux which hasn't Pi-hole installed, i have Pi-hole installed in a docker, what i can do to connect the PADD script to the Pi-hole without them being onto the same machine.
Sorry for bad English.

**Comment by thomasmerz** [comment]
You should copy `padd.sh` to your linux-with-pihole in this (the first) directory `/home/thomas/dev/github/docker-pi-hole/etc-pihole` so it's accessible inside docker container:
```
$ docker inspect pihole | grep /etc/pihole
                "/home/thomas/dev/github/docker-pi-hole/etc-pihole:/etc/pihole:rw"
                "Destination": "/etc/pihole",
                "/etc/pihole": {}
```

Then you can do this (assuming that you are able to ssh to your linux-with-pihole):
```
$ docker -H ssh://root@linux-with-pihole exec -it pihole pihole -v
$ docker -H ssh://root@linux-with-pihole exec -it pihole /etc/pihole/padd.sh
```

This shows up to this:

<img width="587" alt="grafik" src="https://user-images.githubusercontent.com/18568381/154811768-35386976-ada3-44d9-b002-a0b9a28662a0.png">

**Comment by thomasmerz** [comment]
@EndreEndi , does this solve your problem and answer your question? If this is the case, this issue should be closed. See also my [comment](https://github.com/pi-hole/PADD/pull/155#issuecomment-1045327841) in PR #155.

**Comment by thomasmerz** [comment]
I think I provided a solution for this issue. Can someone close this please? Thanks a lot 👍🏻

**Comment by EndreEndi** [comment]
Hi, sorry for the long time response, i don't really check Github a lot, i will close it for now, and try later the solution, Thank you for helping if works, if not, thanks for trying :)

**Comment by EndreEndi** [comment]
Hi again, i 'm a bit stuck, my container name is pihole-template
![image](https://user-images.githubusercontent.com/14347302/159110322-23a5c4cf-46ae-4290-8c44-704c1fd1c293.png)
i was trying to find where to put the name of the container

**Comment by EndreEndi** [comment]
I made it work, sorry for open / close spam, Thank you.
![image](https://user-images.githubusercontent.com/14347302/159110693-beca0ed8-8c03-46f1-9c2d-f1627c0c9d27.png)

**Comment by thomasmerz** [comment]
It was me a pleasure to help you, @EndreEndi 😃
