### ISSUE TITLE
PADD 3.6.4 Shows as out of date

### ISSUE THREAD

**Issue by DesktopECHO** [pi-hole/PADD#192]
Looks like you need formalize release 3.6.4 on GitHub.  
Right now latest is showing 3.6.3 but PADD uses release tags to figure out if it's current.

``padd_version_latest=$(json_extract tag_name "$(curl -s 'https://api.github.com/repos/pi-hole/PADD/releases/latest' 2> /dev/null)")``

![image](https://user-images.githubusercontent.com/33142753/152739860-a9aadb36-3353-489e-b180-78018c8815ef.png)

![image](https://user-images.githubusercontent.com/33142753/152740449-d093ed88-0eca-469e-b55b-fefc1726e216.png)

**Comment by dschaper** [comment]
Thanks, I just tagged that for a release. Should see it correctly now.

**Comment by DesktopECHO** [comment]
Looks good, thank you kindly!
