### ISSUE TITLE
What is the current release?

### ISSUE THREAD

**Issue by Falconcrest** [pi-hole/PADD#199]
Sorry I'm a little confused.
It can be seen here that the latest release is 3.6.5, but Padd shows me on the display that 3.6.6 is installed.
To further confuse it, it says there still updates are available. Is there an explanation?

Pi-hole® v5.9, Web v5.11, FTL v5.14, PADD v3.6.6
[✓] Core  [✓] FTL   [i] Updates are available.

Pi-hole is up to date

root@pihole:~# pihole -v
  Pi-hole version is v5.9 (Latest: v5.9)
  AdminLTE version is v5.11 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)

**Comment by PromoFaux** [comment]
Should be 3.6.6, looks like we forgot the tag.

The versioning on this repo needs some work!

**Comment by Falconcrest** [comment]
Everything fine again..
Thank you for the quick adjustment.
