### ISSUE TITLE
PADD wont update

### ISSUE THREAD

**Issue by dutchschaefer** [pi-hole/PADD#214]
pihole version - v5.9.1 web v5.11. ftl v5.14

**Describe the bug**
Have tried a few different ways to update PADD but after rebooting it still shows as updates are available.

**To Reproduce**
Tried: cd ~
wget -N https://raw.githubusercontent.com/pi-hole/PADD/master/padd.sh
Also
pihole -up
also
pihole -r among a few other options that I can't remember over the past few days.

**Expected behavior**
pi-hole reboots but still shows the same error:  PADD v3.6.7. [i] updates are available

**Comment by Falconcrest** [comment]
Unfortunately I have to confirm this behavior.

**Comment by dschaper** [comment]
Can you run a `head -n 30 padd.sh` on your system so we can see what version you have locally?

**Comment by iamenderst** [comment]
Got the same here:
# VERSION
padd_version="v3.6.7"

**Comment by dutchschaefer** [comment]
<img width="563" alt="Screen Shot 2022-04-18 at 1 40 32 PM" src="https://user-images.githubusercontent.com/99699201/163849569-5012aefc-06c6-452b-8def-99671d2e1065.png">

**Comment by Falconcrest** [comment]
the same thing

# VERSION
padd_version="v3.6.7"

**Comment by dschaper** [comment]
You have the latest version. I think what you are seeing is not that PADD has updates available but instead that Pi-hole has updates available. There was a glitch on GitHub that reset the AdminLTE v5.11 release and that has been fixed. It will take some time to reflect that fix or you can run `rm /etc/pihole/GitHubVersions` and force a new check.

**Comment by Falconcrest** [comment]
That was the solution to the riddle! Thanks!

**Comment by dutchschaefer** [comment]
<img width="516" alt="Screen Shot 2022-04-18 at 2 55 06 PM" src="https://user-images.githubusercontent.com/99699201/163860127-83ca51be-d40b-4a2e-a95d-eb7429c2f14f.png">

I am not the greatest at coding so what am I doing wrong?

**Comment by iamenderst** [comment]
> 

sudo rm /etc/pihole/GitHubVersions

**Comment by dutchschaefer** [comment]
Thanks that worked!
