### ISSUE TITLE
Add Model of Raspberry PI

### ISSUE THREAD

**Issue by lastsamurai26** [pi-hole/PADD#228]
in the version of the chronometer which is supplied with the Pihole, 
the model was then and is still displayed. Is there a possibility to do this here too ?

```
`#######################
    if command -v vcgencmd &> /dev/null; then
        local sys_throttle_raw
        local sys_rev_raw

        sys_throttle_raw=$(vgt=$(sudo vcgencmd get_throttled); echo "${vgt##*x}")

        # Active Throttle Notice: https://bit.ly/2gnunOo
        if [[ "$sys_throttle_raw" != "0" ]]; then
            case "$sys_throttle_raw" in
                *0001) thr_type="${COL_YELLOW}Under Voltage";;
                *0002) thr_type="${COL_LIGHT_BLUE}Arm Freq Cap";;
                *0003) thr_type="${COL_YELLOW}UV${COL_DARK_GRAY},${COL_NC} ${COL_LIGHT_BLUE}AFC";;
                *0004) thr_type="${COL_LIGHT_RED}Throttled";;
                *0005) thr_type="${COL_YELLOW}UV${COL_DARK_GRAY},${COL_NC} ${COL_LIGHT_RED}TT";;
                *0006) thr_type="${COL_LIGHT_BLUE}AFC${COL_DARK_GRAY},${COL_NC} ${COL_LIGHT_RED}TT";;
                *0007) thr_type="${COL_YELLOW}UV${COL_DARK_GRAY},${COL_NC} ${COL_LIGHT_BLUE}AFC${COL_DARK_GRAY},${COL_NC} ${COL_LIGHT_RED}TT";;
            esac
        [[ -n "$thr_type" ]] && sys_throttle="$thr_type${COL_DARK_GRAY}"
        fi

sys_rev_raw=$(awk '/Revision/ {print $3}' < /proc/cpuinfo)
        case "$sys_rev_raw" in
            000[2-6]) sys_model=" 1, Model B";; # 256MB
            000[7-9]) sys_model=" 1, Model A";; # 256MB
            000d|000e|000f) sys_model=" 1, Model B";; # 512MB
            0010|0013) sys_model=" 1, Model B+";; # 512MB
            0012|0015) sys_model=" 1, Model A+";; # 256MB
            a0104[0-1]|a21041|a22042) sys_model=" 2, Model B";; # 1GB
            900021) sys_model=" 1, Model A+";; # 512MB
            900032) sys_model=" 1, Model B+";; # 512MB
            90009[2-3]|920093) sys_model=" Zero";; # 512MB
            9000c1) sys_model=" Zero W";; # 512MB
            a02082|a[2-3]2082) sys_model=" 3, Model B";; # 1GB
            a020d3) sys_model=" 3, Model B+";; # 1GB
            *) sys_model="";;
        esac
        sys_type="Raspberry Pi$sys_model"
    else
        source "/etc/os-release"
        CODENAME=$(sed 's/[()]//g' <<< "${VERSION/* /}")
        sys_type="${NAME/ */} ${CODENAME^} $VERSION_ID"
    fi
#################`
```

This is the code, but it doesn't work with #!/usr/bin/env sh  only with #!/usr/bin/env bash

**Comment by yubiuser** [comment]
This code block was never part of PADD, but only chronometer. This has nothing to do with

**Comment by dschaper** [comment]
I think this is a good idea to have. Thanks Yubi for the POSIX conversion.

**Comment by lastsamurai26** [comment]
Thank you, this works :)

**Comment by yubiuser** [comment]
For later reference: https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#new-style-revision-codes-in-use

**Comment by yubiuser** [comment]
@lastsamurai26 

We're thinking about integrating the code in `PADD`- Could you please share at which place you added the code and maybe a screenshot how this would look like.

**Comment by lastsamurai26** [comment]
![Bildschirmfoto 2022-06-15 um 22 06 46](https://user-images.githubusercontent.com/3257844/173917450-188baa90-278e-4be2-9b4f-6be41e3f3c96.png)

I forked the padd repo with my changes 

https://github.com/lastsamurai26/PADD/blob/master/padd.sh

between line 321 and 369 is your code 
on line 782 you can find the model in the Network area
but i guess we can find a better place for this

**Comment by yubiuser** [comment]
Thanks.

> i guess we can find a better place for this

Maybe System?

**Comment by lastsamurai26** [comment]
I just thought since the hostname is in the network, the model may belong to it. I have inserted the code only for the regular screen but maybe you can do this also for the others.


System also sounds good

**Comment by yubiuser** [comment]
I filed a PR which implements this but different than `chronometer` did. 

@lastsamurai26 could you please test https://github.com/pi-hole/PADD/blob/model/padd.sh

**Comment by lastsamurai26** [comment]
Old Version 
![Bildschirmfoto 2022-06-23 um 15 39 26](https://user-images.githubusercontent.com/3257844/175312970-1b90807c-7d41-4820-ad7f-602c63269b1b.png)

New Version
3b +
![Bildschirmfoto 2022-06-23 um 15 39 41](https://user-images.githubusercontent.com/3257844/175313021-01b44db6-3dc4-4a56-859d-ad68b2f31de0.png)

3B
![Bildschirmfoto 2022-06-23 um 15 47 36](https://user-images.githubusercontent.com/3257844/175314813-e4f6f9b3-e47c-4927-863c-ff662ec3be0a.png)

I unfortunately do not know why the error comes on the 3B

**Comment by yubiuser** [comment]
Thanks for testing. The warning should be fixed not. Please try again.

**Comment by lastsamurai26** [comment]
thx :-)
![Bildschirmfoto 2022-06-23 um 18 52 36](https://user-images.githubusercontent.com/3257844/175353028-a4f54372-0989-4110-90e1-dabe736963a7.png)
![Bildschirmfoto 2022-06-23 um 18 52 47](https://user-images.githubusercontent.com/3257844/175353060-183efc08-88a8-41fb-9631-660241550657.png)
 
error message has disappeared  👍 👍

**Comment by yubiuser** [comment]
Implemented with https://github.com/pi-hole/PADD/releases/tag/v3.8.0
