### ISSUE TITLE
Unexpected color changes in newest update

### ISSUE THREAD

**Issue by bctstkla** [pi-hole/PADD#246]
Hi,

after updating padd there are unexpected color changes that do not look good at all.
Was there some reason for this change and how do I revert the colors to the original ones?
(Other than running an older version of padd from now on.)

![padd_colors](https://user-images.githubusercontent.com/109463439/179395479-cfe088ed-80c8-4418-ba82-49fa0c4e2b9a.png)

**Comment by yubiuser** [comment]
We did not change any colors. Maybe your `sh` uses a different color schema than `bash`. Please try to change the first line in the script from `#!/usr/bin/env sh` to `#!/usr/bin/env bash`

and see if this resolves your issue.

**Comment by bctstkla** [comment]
Hi @yubiuser and thanks for your suggestion, the line in question does indeed differ between the old and new version of padd.sh. Unfortunately modifying the file only changes the behavior (colors) when connected to the Pi with PuTTY and running PADD, but running it on the LCD of the Pi still has these weird colors. Even if I run padd.sh manually on the Pi by hooking up a keyboard.

**Comment by bctstkla** [comment]
I ran a text comparison between the working an non-working version, and the culprit is changes in the color definitions (below).
![image](https://user-images.githubusercontent.com/109463439/179422656-71727c38-88cd-485c-902e-fb689497a7d2.png)

I reverted these changes, and now the color are back to the expected way.

**Comment by yubiuser** [comment]
The change was made by PR https://github.com/pi-hole/PADD/pull/171

**Comment by dschaper** [comment]
Can you get the term type for your setup?

`echo $TERM`

**Comment by bctstkla** [comment]
Hi @dschaper,
running directly from raspberry's terminal (with the lcd) the term type is "linux" and the color outputted is that weird neon-white-yellowish.

Running via ssh and putty, term type is xterm and the color is the expected (green).

**Comment by dschaper** [comment]
Thanks, it seems that the issue is the terminal type. I don't remember offhand how to set the `tty`s to a term that would render the correct escape codes. It may be in the default system `.profile`?
