### ISSUE TITLE
"Slim" does not use all available rows.

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/PADD#279]
"Slim" is used when the console height is 21 (rows). However, we only use 20 and 1 of those is even empty.
https://github.com/pi-hole/PADD/blob/9218e0d587bdd8c3c3ab7ae2aeb75f7a9148af72/padd.sh#L734

We could use this space e.g. to display version information.
See comparison to regular, which needs 22 rows.

![Screenshot at 2022-12-05 21-15-21](https://user-images.githubusercontent.com/26622301/205735085-e52ed085-b854-4c79-84e1-6950e5d2837c.png)
![Screenshot at 2022-12-05 20-56-13](https://user-images.githubusercontent.com/26622301/205735080-3166e806-76ce-4829-b0a2-12991f8bc644.png)

**Comment by rdwebdesign** [comment]
Actually, Mega has the same problem.
80 columns, but only 79 are used.

**Comment by rdwebdesign** [comment]
![PADD_80_79](https://user-images.githubusercontent.com/1385443/205744033-d41b951d-d24b-4c83-81d9-99b420b4c06e.gif)

**Comment by yubiuser** [comment]
Fixed with https://github.com/pi-hole/PADD/commit/ed3657f6a7c52e735c438cb534b13a9f73c9ea37 and https://github.com/pi-hole/PADD/pull/327

**Comment by yubiuser** [comment]
Fix released with https://github.com/pi-hole/PADD/releases/tag/v3.10.1
