### ISSUE TITLE
Latest versions of Pihole, Web, and FTL show up Red in PADDtiny

### ISSUE THREAD

**Issue by bob787** [pi-hole/PADD#289]
I have PADD, pihole, etc running on a Rpi 3B+ and a 3.5" screen. It works great... except the version numbers for Pihole, Web, and FTL all show up as **Red**, despite being the latest versions. See photo

I recall there was a similar same issue in the middle of last month so I skipped that update. I hoped that this update would fix it.

I tried: Updating pihole, updating PADD, restarting

Any advice of guidance is appreciated,

![IMG_0901 Large](https://user-images.githubusercontent.com/98560908/207172445-572da783-6b98-4456-aa4f-17520236b2a5.jpeg)

**Comment by rdwebdesign** [comment]
Duplicate.
This is the same issue as https://github.com/pi-hole/PADD/issues/287, moved to Pi-hole https://github.com/pi-hole/pi-hole/issues/5059.

Please, post your comments there. It will be easier to find a solution with all information on the same place.
