### ISSUE TITLE
Pi-hole not up to date?

### ISSUE THREAD

**Issue by Falconcrest** [pi-hole/PADD#299]
Hello.

since yesterday evening, PADD has been showing me that Pi-hole and Web should no longer be up to date.

![Pic](https://user-images.githubusercontent.com/20321911/208237717-253400eb-168f-4448-8876-11a6536ff7f3.jpg)

But when I run pihole -up and pihole -v everything seems up to date.

`root@pihole:~# pihole -up
  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.4.33
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for dialog
  [✓] Checking for ca-certificates

  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              up to date

  [✓] Everything is up to date!
root@pihole:~# pihole -v
  Pi-hole version is v5.14.2 (Latest: v5.14.2)
  AdminLTE version is v5.17 (Latest: v5.17)
  FTL version is v5.19.2 (Latest: v5.19.2)`

What does PADD know more than pihole itself? ;-)

**Comment by yubiuser** [comment]
Your likely affected by `https://github.com/pi-hole/pi-hole/issues/5059`
