### ISSUE TITLE
README file needs update

### ISSUE THREAD

**Issue by rdwebdesign** [pi-hole/PADD#314]
# Describe the issue

Current Pi-hole images already have PADD installed, making the section "_Running Pi-hole in a Docker Container_" completely outdated.
 
# Expected behavior

Remove the obsolete text and add information about running PADD on docker-pi-hole images.

Now, only this command is needed:
```console
docker exec -it <container_name> padd [padd_options]
```

**Comment by yubiuser** [comment]
Pinging @thomasmerz 

https://github.com/pi-hole/docker-pi-hole/pull/1105#issuecomment-1212969766
