### ISSUE TITLE
"Updates are available" when using Pi-hole in Docker Container but "unable" to update PADD

### ISSUE THREAD

**Issue by thomasmerz** [pi-hole/PADD#324]
**Describe the bug**
I'm running Pi-hole in a Docker Container with "latest" everything. But `PADD` could be updated, but it couldn't be updated until Docker Image will get this update. This might irritate or "frustate" users:
```
 __      __  __   
|__) /\ |  \|  \     Pi-hole® v5.14.2, Web v5.18, FTL v5.20, PADD v3.9.0
|   /--\|__/|__/     [✓] Core  [✓] FTL   [i] Updates are available
```

**Expected behavior**
I'm not exactly sure how `PADD` should inform Docker users that there is an update available for `PADD`… Maybe **let's discuss if this is not neccessary for Docker because Docker Images should always be considered as an All-in-One**!? 🤔  Or do you prefer an update-strategy **inside** a running Docker Container?

**Screenshots**
`docker exec -it pihole padd`
![image](https://user-images.githubusercontent.com/18568381/210175516-18d777c8-a43f-42fd-aa8f-69a716fbacff.png)

https://github.com/pi-hole/PADD/
![image](https://user-images.githubusercontent.com/18568381/210175413-3f4029db-103a-4052-885e-616224238114.png)

https://github.com/pi-hole/docker-pi-hole/
![image](https://user-images.githubusercontent.com/18568381/210175440-ede2d7df-1194-4330-a7b2-9d162b37af2b.png)

**Comment by PromoFaux** [comment]
Ah, I had not realised there was a new version tagged - busy time of year. 

New docker image building as we speak (We'll pretend that it was tagged 2 days ago 😉 )
https://github.com/pi-hole/docker-pi-hole/actions/runs/3817491391

I think there should be something added to PADD that says "If it is inside docker, don't display the update notice", like we have for the web/core components

**Comment by PromoFaux** [comment]
> but it couldn't be updated until Docker Image will get this update.

Technically it could be overwritten inside the container if one was desperate for the latest PADD. It lives at `/usr/local/bin/padd` inside the container. Obviously any changes made would be lost on restarting the container.

**Comment by thomasmerz** [comment]
That's not what containers are made for (inplace-patching)… Ideas so far:
- Do not check for latest version because there's no good way to update it when no Pi-hole docker image is available.
- Download latest `PADD` on each container start which would fix this.

**Comment by yubiuser** [comment]
Fix released with https://github.com/pi-hole/PADD/releases/tag/v3.10.1

**Comment by thomasmerz** [comment]
`Docker 2023.01.3, PADD v3.10.1`- and after a short amount of time: `Docker 2023.01.4, PADD v3.10.1` 👍🏼
