### ISSUE TITLE
Screen issues with Hyperpixel 4 and v3.10.1

### ISSUE THREAD

**Issue by coujin11** [pi-hole/PADD#339]
After updating to V3.10.1 and rebooting my Pi4 - I am getting screen issues.lines

Any advise on this and is there an easy way to roll back to v3.10.0?

**Comment by coujin11** [comment]
![IMG_1114 (1)](https://user-images.githubusercontent.com/123183754/213730755-5b134d33-83b8-41fc-95b6-ec978380ca9c.jpg)

**Comment by coujin11** [comment]
I have downgraded back to V3.10.0 but is problem is still present

**Comment by PromoFaux** [comment]
What screen is that? Looks like it may be an issue with the hardware?

**Comment by coujin11** [comment]
It was working perfectly fine before hand. I have uploaded a photo

**Comment by coujin11** [comment]
Hyperpixel 4 - I was ordering completely fine before the update/reboot

**Comment by yubiuser** [comment]
I agree with **PromoFauy**: this looks like a hardware issue. Esp. as the issue persists after downgrading. I think we have more users with Hyperpixel 4, let's see if they observe the same issue.

**Comment by PromoFaux** [comment]
I've got one on order - will be able to confirm once it arrives

**Comment by PromoFaux** [comment]
I have received it. I have no idea how to set it up. I will read the docs again later!!

**Comment by PromoFaux** [comment]
I have the orientation set the opposite of yours, however all looks good here:

![image](https://user-images.githubusercontent.com/1998970/214519542-e110f5e8-644f-4ea3-808c-86946a3b75fa.png)

I suspect your screen has a hardware issue - or could be an issue with display drivers (@gadgetoid - feel free to ignore this ping if you like, but if you have any advice it would be appreciated)

You could also take a look at : https://github.com/pimoroni/hyperpixel4/issues/177

I needed to refer to that when setting up the screen on this Raspberry Pi 3b, but same applies to the 4.

**Comment by nineteenletterslong** [comment]
I have a hyperpixel 4 as well. Is there a way padd can utilize the entire screen like this hack? https://gist.github.com/giuliomagnifico/91344ab9b3f304aaec5ff3fa90ad22e3

The author hasn't updated it for 3.10.1 changes and has to update every time padd updates but it would be nice if the official padd release could accommodate these changes for larger screen users

**Comment by yubiuser** [comment]
Pull requests are always appreciated :⁠-⁠)

**Comment by nineteenletterslong** [comment]
Took it upon myself to use a diff program to merge changes. Here's a version 3.10.1 for hyperpixel 4

https://pastebin.com/N2Nttzkt

**Comment by yubiuser** [comment]
Both versions display some unbound stats without replacing them in case unbound is not installed (or `unbound-control` is not enabled). I think we should not add something to the 'official' PADD that displays infos from a certain external software. Other users might want `cloudflared` stats displayed, other XYZ stats...

**Comment by nineteenletterslong** [comment]
Oh that’s right, I forgot that was an addition Giulio made, should be a quick fix
