### ISSUE TITLE
PADD information not being refreshed

### ISSUE THREAD

**Issue by sastromo** [pi-hole/PADD#340]
Information is not being refreshed.
There are four errors showing:
> cat: '': No such file or directory
> ./padd.sh: 195: [: -gt: unexpected operator
> ./padd.sh: 199: [: -gt: unexpected operator
> ./padd.sh: 201: [: -gt: unexpected operator

![Screenshot_12](https://user-images.githubusercontent.com/45545544/220939651-10e8d917-f8df-4c5a-884a-1c028eecabf6.png)

- Running Pi-hole on an **x86** with **DietPi**.
- Same problem via SSH.
- Same error even after reinstalling.

Any help would be amazing
Thanks!

**Comment by yubiuser** [comment]
What's the output of 

```
ls -lha /sys/devices/platform/coretemp.0/hwmon/
ls -lha /sys/class/thermal/thermal_zone0/
ls -lha /sys/class/hwmon/hwmon0/

```

**Comment by rdwebdesign** [comment]
`cat` (lines 165-169) is returning an empty string and storing into `cpu` variable. 
The test fails because the `-gt` operator expects an integer.

**Comment by yubiuser** [comment]
It likely fails here:
https://github.com/pi-hole/PADD/blob/a9681264c83529a2bd826bc86dd933d85b9b15bf/padd.sh#L164

Please check if there is a file `temp1_input` within `/sys/devices/platform/coretemp.0/hwmon/hwmon3`

**Comment by rdwebdesign** [comment]
You need to use this link to download the file:
https://raw.githubusercontent.com/pi-hole/PADD/empty_temp/padd.sh

**Comment by rdwebdesign** [comment]
Ok... The error is still there, but now the temperature is not `0.0°C`.

**Comment by rdwebdesign** [comment]
@sastromo 

I changed the code.

Could you try again (`wget -N https://raw.githubusercontent.com/pi-hole/PADD/empty_temp/padd.sh`)?

**Comment by yubiuser** [comment]
The dashboard should refresh every 5 seconds.
