### ISSUE TITLE
PADD display shifted up wards and not returned to normal after long domain displayed

### ISSUE THREAD

**Issue by cmdshft** [pi-hole/PADD#56]
*Before submitting a bug report, are you using a test version of Pi-hole? If so, PADD doesn‘t support beta versions of Pi-hole!*

**Describe the bug**
When a very long domain is displayed on PADD output, the entire CLI is shifted upwards. It does not return to a normal display after a new shorter domain is displayed

**To Reproduce**
1. have a long domain displayed

**Expected behavior**
Scroll long domain instead?

**Screenshots**
![IMG_1372](https://user-images.githubusercontent.com/8571823/56517532-20274180-650b-11e9-9d00-b9acffe82e24.jpg)

**Comment by R3clu23** [comment]
I to am having the same issue with my display shifting up.  
I'm running:
Pi-Hole v4.4 [green]
Web v4.3.3 [green]
FTL v4.3.1 [green]
PADD v3.1 [red]

I have run the PiPadd update twice, not change.

pi@Pihole:~ $ wget -N https://raw.githubusercontent.com/jpmck/PADD/master/padd.sh
--2020-02-29 13:36:04--  https://raw.githubusercontent.com/jpmck/PADD/master/padd.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 43103 (42K) [text/plain]
Saving to: ‘padd.sh’

100%[====================================>]  42.09K  --.-KB/s    in 0.04s

Last-modified header missing -- time-stamps turned off.
2020-02-29 13:36:04 (1009 KB/s) - ‘padd.sh’ saved [43103/43103]
              
![20200229_132949](https://user-images.githubusercontent.com/23437687/75613186-c1eac800-5af8-11ea-9fbf-343295abcc72.jpg)

**Comment by yubiuser** [comment]
This is a quite old issue, but meanwhile it was solved. The display is still shifted with a very long domain but returns to normal if the next one is a "normal" sized domain.

![Peek 2022-08-20 22-39](https://user-images.githubusercontent.com/26622301/185765290-6ef187f7-741d-4bd2-a70d-8f1db3ad3a3b.gif)
