### ISSUE TITLE
abnormally high cpu usage with latest update 3.1

### ISSUE THREAD

**Issue by famesjranko** [pi-hole/PADD#77]
**Describe the bug**
Noted abnormally high cpu usage with latest update - +90%

**To Reproduce**
1. ... pull latest build
2. ... run padd.sh

**Expected behavior**
padd to execute and run as previous builds. 

**Additional context**
reverted back to previous build and cpu usage returned to normal.
running non-beta pihole (v4.3.3) on a raspberry pi zero.

**Comment by ferazambuja** [comment]
Same here

**Comment by robogeek78** [comment]
I am seeing something similar, However, /proc/loadavg is reporting upwards of .9 to 1.5.

If I use iostat, i am seeing more like 30% loading.

**Comment by dschaper** [comment]
Still seeing this issue?

**Comment by robogeek78** [comment]
I just checked and I am no longer seeing this issue.
