### ISSUE TITLE
Color distortion

### ISSUE THREAD

**Issue by chrisjeb** [pi-hole/PADD#78]
*Before submitting a bug report, are you using a test version of Pi-hole? If so, PADD doesn‘t support beta versions of Pi-hole!*

**Describe the bug**
After 3.1 update my 3.5 screen has a yellowish tint to it

**To Reproduce**
1. ...
2. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dschaper** [comment]
That's a hardware issue then. Colors are just codes sent to the terminal emulator. How the actual colors are displayed is handled by the screen and the terminal emulator.
