### ISSUE TITLE
PADDmini Load/Memory alignment issue

### ISSUE THREAD

**Issue by christianboyle** [pi-hole/PADD#79]
Not sure if [this commit](https://github.com/jpmck/PADD/commit/94483123481abcd5c61fd9dc2dd8902506e933b7#diff-f0d2b00f20028b2c7f9febd84b9659afL756) has anything to do with it, but it seems like the [latest update (3.1)](https://github.com/jpmck/PADD/releases/tag/v3.1) has unset the indentation of the `Load` and `Memory` labels in PADDmini as well as the alignment of the `Load` and `Memory` bars.

Post-update:
![2020-02-25_01-20-48PM](https://user-images.githubusercontent.com/1605754/75279775-d1ed6980-57d1-11ea-93ec-4625706269cd.png)

Pre-update:
![68747470733a2f2f6a706d636b2e636f6d2f696d672f706164642f346d696e692e706e67](https://user-images.githubusercontent.com/1605754/75279559-699e8800-57d1-11ea-8746-fba1ce1baa7b.png)

**Comment by Profesyor** [comment]
And me wanting PADDmini to use my WHOLE 2.8 screen.

**Comment by christianboyle** [comment]
Fixed here: https://github.com/jpmck/PADD/pull/83

**Comment by christianboyle** [comment]
This will be fixed in an [upcoming release](https://github.com/pi-hole/PADD/pull/118).
