### ISSUE TITLE
PADDmini - update and size?

### ISSUE THREAD

**Issue by Sisko4** [pi-hole/PADD#89]
Hello!
I just installed pihole and the padd plugin, but i have two problems:

1: The Plugin says "PADDmini [i] Update avail."
But i already did an update and reboot everything.
How can i get that solved?

2: Can i use other sizes like the regular info screen on a 2,8" PiTFT?

![PADD](https://user-images.githubusercontent.com/55309673/76518299-242fbb00-645f-11ea-876f-fc455fcfa53c.jpg)

**Comment by Kerdic** [comment]
[check out this link](https://github.com/jpmck/PADD/issues/86), I have a customized script to support 2.8 screens. But at the moment, there is no official support.

Ignore the update avail until the next official build, it is a bug mentioned in other issues here, and there are multiple pull requests that address the issue. I modified my script to address the bug, but not in the most elegant way.

**Comment by Sisko4** [comment]
Ah okay thanks! Yours looks way better than this, they should implemend it!

**Comment by Profesyor** [comment]
Also update Pi-hole:
 pihole -up

**Comment by Sisko4** [comment]
Already did that before posting, everything up-to-date.

**Comment by Profesyor** [comment]
Have you updated line 439 on the original padd.sh from Location to location?

**Comment by Profesyor** [comment]
Use @Kerdic latest file, he got that also covered.

**Comment by dschaper** [comment]
"Tiny" is now in the master branch, release v3.3
