### ISSUE TITLE
PADD reports "Pi-hole is offline" after temporarily disabling Pi-hole

### ISSUE THREAD

**Issue by aidenmitchell** [pi-hole/PADD#94]
*Before submitting a bug report, are you using a test version of Pi-hole? If so, PADD doesn‘t support beta versions of Pi-hole!*

**Describe the bug**
PADD reports "Pi-hole is offline" after temporarily disabling Pi-hole through the Web UI.

**To Reproduce**
1. Disable Pi-hole throrugh Web UI
2. Enable Pi-hole thorough Web UI

**Expected behavior**
PADD reports System is healthy.

**Comment by PA3DSS** [comment]
I have the same issue

**Comment by dschaper** [comment]
Is this still an issue?

**Comment by KnownAim** [comment]
Yes. PADD seems to recognize fairly quickly that Pi-hole is offline, but is unable to recognize as quickly that it is back online.

**Comment by dschaper** [comment]
It would help if someone could test the current version and report if this is still an issue.

**Comment by KnownAim** [comment]
I disabled PiHole for 10 seconds, after which PADD reported "Pi-hole is offline." It has been 5 hours since then, and PADD still reports Pi-hole as offline despite it running properly.

**Comment by dschaper** [comment]
Thank you for checking. I'll leave the issue open then.

**Comment by KnownAim** [comment]
No problem. #54 is the same issue, if you wanted to close one of them.

**Comment by lastsamurai26** [comment]
The problem is still present with the latest version

**Comment by subnut** [comment]
@lastsamurai26 You are using PADD in _mega_ mode, right?

In _my_ testing, I have found that this issue occurs only on the _mega_ mode.

**Comment by lastsamurai26** [comment]
> @lastsamurai26 You are using PADD in _mega_ mode, right?
> 
> In _my_ testing, I have found that this issue occurs only on the _mega_ mode.

correct i use the mega mode

**Comment by subnut** [comment]
Can everyone please test if #167 fixes the issue?

**Comment by lastsamurai26** [comment]
> Can everyone please test if #167 fixes the issue?

for me it works now

**Comment by KnownAim** [comment]
Can this be pushed to a new release? Thought it would be in the latest
update but it wasn't included.
